PARSER_BEGIN(ABCParser)
public class ABCParser {
    public static void main(String[] args) throws ParseException {
        new ABCParser(System.in).S();
    }
}
PARSER_END(ABCParser)
SKIP : { " " | "\t" | "\r" | "\n" }
TOKEN : { "(" | ")" | "+" | "-" | "*" | <NUM: (["1"-"9"])+ (["0"-"9"])*> }
void S() :
{}
{
    A()
}

void A() :
{}
{
    B() ( ("+" B() )*
}
void B() :
{}
{
    C() ("*" C())*
}
void C() :
{}
{
    <NUM>
    |
    "(" ( C() )* ")"
}
