PARSER_BEGIN(Parser)

public class Parser {
	public static void main(String[] args) throws Exception {
		new Parser(System.in).S();
	}
}

PARSER_END(Parser)

SKIP:  { " " | "\t" | "\r" }
TOKEN: { "(" | ")" | "+" | "*" | <NUM: (["0"-"9"])+> }

void S(): 
{}
{
	E() "\n" 
}

void E(): 
{
	System.out.print("E->");
}
{
	T() ("+" T() )* 
}

void T(): 
{
	System.out.print("T->");
}
{
	F() ("*" F() )* 
}

void F(): 
{
	System.out.print("F->");
}
{
	<NUM> 
|
	"(" E() ")" 
}